In [1]:
# Import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [2]:
# Load the data
from google.colab import files
uploaded = files.upload()

Saving spamham.csv to spamham.csv


In [4]:
df = pd.read_csv("spamham.csv")
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df["text"], df["spam"], test_size=0.25, random_state=0)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 5, 0, ..., 0, 0, 0],
       [0, 0, 4, ..., 0, 0, 0]])

In [17]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [18]:
emails = [
      "Up to 20% discount on buying right now!! Exlusive offer for you!!",
      "Good morning, John. Can we get together to watch football game tomorrow?"
]

In [20]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([1, 0])

In [21]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9894662921348315

In [22]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
      ('vectorizer', CountVectorizer()),
      ('nb', MultinomialNB())
])

In [23]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [24]:
clf.score(X_test, y_test)

0.9894662921348315

In [25]:
clf.predict(emails)

array([1, 0])